version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: braiins-braiins-manager-agent_web_1
      APP_PORT: 8080

  web:
    # TODO: move to a Braiins-owned registry before official-store submission
    image: ghcr.io/tgr-braiins/braiins-manager-agent:4.10.0@sha256:ff5db6e6cb05e4098c4f39ae0461ef4f574937b9c6bf863d0e3750b2dfab35a0
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
